# Generated by Django 3.2.9 on 2021-11-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_cryptocurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='current_price',
            field=models.FloatField(null=True),
        ),
    ]
