# Generated by Django 3.2.9 on 2021-11-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_cryptocurrency_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='current_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
